name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      instancle-url:
        type: string
        description: to overwrite the instace to test against

jobs:
  greet:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: pop env
      run:  if [ -n "${{ github.event.inputs.instancle-url }}" ]; then echo "CYPRSS_INSTANCE_URL=${{ github.event.inputs.instancle-url }}" >> $GITHUB_ENV; fi 
    - name: Send greeting
      run: echo "${{ github.event.inputs.environment }}" && bla='${{ secrets.CYPRESS_TEACHER_PASSWORD }}' && echo "${#bla}"
    - name: verify optEnv
      run: echo "fff $CYPRSS_INSTANCE_URL"
