name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.environment }}" && echo "secret ${{ secrets.CYPRESS_TEACHER_PASSWORD }}"
